config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :users, only: [:index, :new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]  
  get '/login', to: 'sessions#new'

  resources :posts do
    resources :comments, only: [:show, :create, :destroy, :edit, :update]
  end

  # Don't know why I had to do this - band aid fix
  delete '/comment/:id', to: 'comments#destroy', as: 'comment' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_attached_file :pic
  validates_attachment :pic, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_attached_file :pic
  validates_attachment :pic, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  has_many :comments, dependent: :destroy
  validates :title, :presence => true
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  
    helper_method :current_user
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to post_path(params[:post_id])
    else
      render :new
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    post = comment.post
    comment.destroy
    redirect_to post_path(post)
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end
  
  private
  
  
  def comment_params
    params.require(:comment).permit(:content, :pic)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @post.id = (params[:id])
    @comment = Comment.new    
  end

  def new
    if !current_user.nil?
      @post_new = Post.new
    end
  end

  def create
    @post = current_user.posts.new(post_params)
    if !@post.title.blank? && @post.save
      flash[:notice] = "Post created successfully."
      redirect_to post_path(@post.id)
    else
      redirect_to new_post_path
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
    flash[:notice] = "Post deleted successfully."
  end
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(params.require(:post).permit(:title))
        format.html { redirect_to post_path(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  
  
  def post_params
    params.require(:post).permit(:title, :pic)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
    def new
    end
  
    def create
      user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path, notice: "Logged in"
      else
        flash.now.alert = "Invalid login credentials, try again."
        render :new
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: "Logged out"
    end
  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all
    @comments = @user.comments.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You have successfully signed up!"
      redirect_to root_path
    else
      render :new
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/show.html.erb
<div class="post-c col-lg-12">
  <%= image_tag @comment.pic.url, :class => "opost img-responsive" %>
</div>
<div class="com">
<h2>Original Thread: <%= link_to @post.title, @post %></h2>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;by: <%=link_to @post.user.username, user_path(@post.user.id)%><br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Papes</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lobster|Muli" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="papes navbar-brand" href="/posts">Papes</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if current_user %>
      <li class="c-container nav-item">
        <a href="/posts/new" class="create btn btn-primary">Create Thread</a>
      </li>
    <%end%>
      
    </ul>
    <ul class="nav navbar-nav navbar-right">
      

      <% if current_user %>
          <li class="nav-item">
            <%= link_to current_user.username, user_path(current_user), class:"acc btn btn-primary" %>
          </li>
          <li>
            <%= link_to 'Log Out', session_path('dummy'), method: :delete, class:"acc btn btn-primary" %>
          </li>
          <% else %>
            <%= link_to "Log In", login_path, class:"acc btn btn-primary" %>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <%= link_to "Sign up", new_user_path, class:"acc btn btn-primary" %>
          <% end %>


    </ul>
  </div>
</nav>

    
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= form_for @post do |f| %>
  <div class="login">

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="actions"><%= f.submit %></div>
    </div>
  <% end %>
<div class="login">
<%= link_to 'Cancel', posts_path %>
</div>

app/views/posts/index.html.erb
<h1>All Threads</h1>
<% @posts.each_with_index do |post,idx| %>
  <%if idx%3==0%>
    <div class="row">
      <%= link_to post_path(post) do %>
        <div class="col-sm-4">
          <div class="card" style="width: 20rem;">
            <img class="card-img-top" src="<%= post.pic %>" alt="Card image cap">
            <div class="card-block">
              <h4 class="card-title"><%=post.title%></h4>
              <p class="card-text"></p>
            </div>
          </div>
        </div>
      <%end%>
  <%elsif idx%3==2 || post == @posts.last%>
  <%= link_to post_path(post) do %>
    <div class="col-sm-4">
      <div class="card" style="width: 20rem;">
        <img class="card-img-top" src="<%= post.pic %>" alt="Card image cap">
        <div class="card-block">
          <h4 class="card-title"><%=post.title%></h4>
          <p class="card-text"></p>
        </div>
      </div>
    </div>
  </div> 
  <%end%>
  <%else%>
    <%= link_to post_path(post) do %>
      <div class="col-sm-4">
        <div class="card" style="width: 20rem;">
          <img class="card-img-top" src="<%= post.pic %>" alt="Card image cap">
          <div class="card-block">
            <h4 class="card-title"><%=post.title%></h4>
            <p class="card-text"></p>
          </div>
        </div>
      </div>
    <%end%>
  <%end%>
<% end %>

app/views/posts/new.html.erb
<h1 class="n-thread">Create New Thread</h1>
<%= form_for @post_new, url: posts_path, html: { multipart: true } do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, required: true %>
    <%= f.file_field :pic, required: true %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/posts/show.html.erb
<div class="post-c col-lg-12">
  <%= image_tag @post.pic.url, :class => "opost img-responsive" %>
</div>

<div class="footer">
  <h2><%= @post.title %><span></span></h2>
  <%if @post.user == current_user%>
    <%= link_to "delete post", post_path(@post), method: :delete %>
    &nbsp;|&nbsp;
    <%= link_to "edit post", edit_post_path(@post) %>
  <%else%>
    <strong>posted by: <%=link_to @post.user.username, user_path(@post.user.id)%></strong><br>
  <%end%>
</div>

<%if current_user%>
  <h1 class="c-title">Comments:</h1>
  <div class="c-form">
  <h4>Submit Comment</h4>
    <%= form_for [@post, @comment], html: { multipart: true } do |f| %>
      <div class="field">
        <%= f.text_field :content %>
        <%= f.file_field :pic %>
        <%= f.submit "comment" %>
      </div>
    <% end %>
  </div>
<%end%>


<% @post.comments.each do |comment| %>
  <%@user = comment.user%>
  <%@comment_id = comment.id%>

    <div class = "comment">
      <strong><%=link_to @user.username, user_path(@user.id)%></strong>:
      <div class="content">
          <%= comment.content %>
        </div>
      <%= link_to post_comment_path(params[:id], comment) do %>
      <%if comment.pic.url != nil%>
        <%= image_tag comment.pic.url, :class => "img-thumbnail" %><br>
      <%end%>
      <% end %>
      <%if comment.user == current_user%>
        <%= link_to "delete comment", comment_path(comment), method: :delete %>
      <%end%>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

  <%= form_for @user do |f| %>
  <div class="login">
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit %></div>
    </div>
  <% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<div class = "row">
  <div class = "col-sm-6">
    <h2>Threads created by <%= @user.username %></h2>
      <% @posts.each do |post| %>
        <%= link_to post do %>
        <h4><%= post.title%></h4>
    <% end %>

    <br>
  <% end %>
  </div>
  <div class = "col-sm-6">
    <h2>Comments created by <%= @user.username %></h2>
    <% @comments.each do |comment| %>
      <h4><%= link_to comment.content, comment.post %></h4>
      <br>
    <% end %>
  </div>
</div>